# -*- coding: utf-8 -*-
"""rock_paper_scissor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MX2tAKqrNdvqHwo3Phuzdneu-MnDpLTl
"""

import random
user=input("'r' for rock,'p' for paper,'s' for scissor : ")
computer=random.choice(['r','p','s'])
print("Computer generated choice : ", computer)
if user == computer:
  print("It\'s a  tie")
elif user != computer:
  print("let\'s see .........")
player = user
opponent = computer
if(player == 'r' and opponent == 's') or (player == 's' and opponent == 'p') or (player == 'p' and opponent =='r'):
    print("oh yeah!! Player won :)")
elif (player == 's' and opponent == 'r') or (player == 'p' and opponent == 's') or (player == 'r' and opponent =='p'):
    print("player lost,computer won :(")