# -*- coding: utf-8 -*-
"""numberguessing(computer).py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RdMyu6YcFvVosLTH_ofAuyhChaHzuhVL
"""

import random

def guess(x):
  random_number=random.randint(1,x)
  guess=0

  while guess != random_number:
    guess=int(input(f"Guess a number between 1 and {x} : " ))
    print(guess)
    if guess < random_number:
      print("Sorry!! Guess again.. too low")
    elif guess > random_number:
      print("Sorry!! guess again..too high")
  print("Congrats..yay.. you guessed the right number!!!!")

guess(int(input("Enter number : ")))