# -*- coding: utf-8 -*-
"""numberguessing(user).py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KTb3xHzkjC0dDBsK6WaWIKjw9gKeHNw9
"""

import random
def computer_guess(x):
  low=1
  high=x
  feedback=''
  while feedback != 'c':
    guess=random.randint(low,high)
    feedback=input(f"Is {guess} too high(h),too low(l) or correct (c) :  ")
    if feedback == 'h':
      high=guess-1
    elif feedback == 'l':
      low=guess+1
  print(f"Yay!! I am the computer and guessed your number right.. i.e. : {guess}")

computer_guess(int(input("Number to guess : ")))