# -*- coding: utf-8 -*-
"""madlibs.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d46k9Trspw3ez7APFHNci7QB2lL8Zou2
"""

#madlibs
verb1=str(input("Enter first verb : "))
verb2=str(input("Enter second verb : "))
verb3=str(input("Enter third verb : "))
verb4=str(input("Enter fourth verb : "))
Adj1=str(input("Enter first adjective : "))
Adj2=str(input("Enter second adjective : "))
noun1=str(input("Enter first noun : "))
noun2=str(input("Eneter second noun : "))
print("\n READ YOUR STORY \n")
madlibs=f"When {noun1} came to {verb1} with {Adj1}, you met {noun2}.They {verb2} their mind and {verb3} in country.They know their {Adj2} and eventually {verb4} .."
print(madlibs)