# -*- coding: utf-8 -*-
"""passwordgenerator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fM-U62m_8JYfxjh_pgh61uOwGtpGB95C
"""

import random

print("Welcome to your password generator!!")

characters="qwertyuiopasdfghjklzxcvbnm`!@#$%^&*()-+.,?1234567890"

length=int(input("Enter desired length of password : "))
print("\n  Suggested passwords for you!! :) ")

passwords=''
for c in range(length):
    passwords+=random.choice(characters)
print(passwords)