# -*- coding: utf-8 -*-
"""abstract_classes_methods.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/162q8z2afEKIZbY_oA0oeD8tJOzl0DeXr
"""

from abc import ABC,abstractmethod
class Shape(ABC):

   @abstractmethod
   def area(self):
    ""
class Rectangle(Shape):

  def __init__(self,width,height):
    self.width=width
    self.height=height
  def area(self):
    return self.width*self.height
rect=Rectangle(9,5)
print("The area of rectangle is : " , rect.area())