# -*- coding: utf-8 -*-
"""10_instance_methods.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LSEOp87m-tdQ0_aBax59dsDHPIh1LS3_
"""

class Dog:
    def __init__(self, name, breed):
        self.name = name
        self.breed = breed

    def bark(self):
      print(f"{self.name} is of breed {self.breed} and only does Woof!!")
Dog1=Dog("Tommy","German Shepherd")
print(Dog1.bark())