# -*- coding: utf-8 -*-
"""11_class_methods.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lwy-77sS6qEVgSs_zDuv4ao2pTPqkgzc
"""

class Book:
    total_books = 0

    def __init__(self, title, author):
        self.title = title
        self.author = author
        Book.increment_book_count()

    @classmethod
    def increment_book_count(cls):
      cls.total_books+=1
b1=Book("Harry Potter","J.K.Rowling")
b2=Book("Mushaf","Nimra Ahmed")
print(f"The total number of books are : {Book.total_books} ")