# -*- coding: utf-8 -*-
"""12_static_methods.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e1Pk7Od6AHq1w5w78vNhsWciV6yMy9cZ
"""

class TemperatureConverter:

    @staticmethod
    def celsius_to_fahrenheit(c):
        return (c * 9/5) + 32


celsius = -5
fahrenheit = TemperatureConverter.celsius_to_fahrenheit(celsius)
print(f"{celsius}°C = {fahrenheit}°F")