# -*- coding: utf-8 -*-
"""13_compostion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xtv9F2csYk-F5ZFpPl4A88639I99iiDf
"""

class Engine:
    def start(self):
        return "Engine has started"

class Car:
    def __init__(self, engine):
        self.engine = engine

    def start_car(self):
        return self.engine.start()

my_engine = Engine()
my_car = Car(my_engine)

print(my_car.start_car())