# -*- coding: utf-8 -*-
"""15_mro_diamond_inheritance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10BjEeSXwUJlrINDoBeMud1jTk9c9PmEF
"""

class A:
    def show(self):
        print("Show method in A")

class B(A):
    def show(self):
        print("Show method in B")

class C(A):
    def show(self):
        print("Show method in C")

class D(B, C):
    print("Lets see what D offers\n oh! see below!!")


d = D()
d.show()


print(D.__mro__)