# -*- coding: utf-8 -*-
"""16_function_decorators.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nNKd8ZztouHYiZaBc9GxlnFXO0zO2LMI
"""

def log_function_call(func):
    def wrapper(*args, **kwargs):
        print("Function is being called")
        return func(*args, **kwargs)
    return wrapper

@log_function_call
def say_hello():
    print("Hello!")


say_hello()