# -*- coding: utf-8 -*-
"""17_class_decorator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16hYGiUmZmEwpUNJACGAGVYW-dmru2h2L
"""

def add_greeting(self):
    def greet(self):
        return "Hi!"
    self.greet = greet
    return self

@add_greeting
class Person:
    def __init__(self, name):
        self.name = name

p = Person("sam")
print(p.greet())