# -*- coding: utf-8 -*-
"""20_custom_exception.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-f30jf7JuI0aaG-2XkbhPM1Btm-VDaBR
"""

class InvalidAgeError(Exception):
    def __init__(self, message="Age must be 18 or older."):
        super().__init__(message)

def check_age(age):
    if age < 18:
        raise InvalidAgeError(f"Invalid age: {age}. You must be at least 18.")
    else:
        print("Access granted.")


try:
    user_age = int(input("Enter your age: "))
    check_age(user_age)
except InvalidAgeError as e:
    print(f"Access denied: {e}")
except ValueError:
    print("Please enter a valid number.")