# -*- coding: utf-8 -*-
"""21_iterableclass.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jBOs8uf9BWLMf7b4ZSv49k1e-TpoyopK
"""

class Countdown:
    def __init__(self, start):
        self.start = start
        self.current = start

    def __iter__(self):
        self.current = self.start
        return self

    def __next__(self):
        if self.current < 0:
            raise StopIteration
        value = self.current
        self.current -= 1
        return value




for num in Countdown(20):
    print(num)
print("Done!!")