# -*- coding: utf-8 -*-
"""countdowntimer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zdz9yW-cbbm4gOhbl66TQ2I1UsBW5o5u
"""

import time

def countdown(t):
  while t:
    minutes,seconds=divmod(t,60)
    timer=f"{minutes:02}:{seconds:02}".format(minutes,seconds)
    print(timer,"\r")
    time.sleep(0.5)
    t-=1
  print("Countdown completed! :) ")

t=input("Enter time in seconds : ")
countdown(int(t))